"""Retraining trigger pipeline -- execution and MLflow integration."""

    def run_pipeline(self) -> bool:
        """
        Execute the full training pipeline as a subprocess.

        Returns:
            True if pipeline completed successfully, False otherwise
        """
        pipeline = Path(self.pipeline_script)
        if not pipeline.exists():
            logger.error("Pipeline script not found: %s", pipeline)
            return False

        logger.info("Starting training pipeline: %s", pipeline)
        try:
            result = subprocess.run(
                [sys.executable, str(pipeline)],
                capture_output=True,
                text=True,
                timeout=3600,  # 1 hour max
                env={**os.environ},
            )
            if result.returncode == 0:
                logger.info("Pipeline completed successfully")
                logger.debug("Pipeline output:\n%s", result.stdout[-2000:])
                return True
            else:
                logger.error(
                    "Pipeline failed (exit code %d):\n%s",
                    result.returncode,
                    result.stderr[-2000:],
                )
                return False
        except subprocess.TimeoutExpired:
            logger.error("Pipeline timed out after 3600s")
            return False
        except (RuntimeError, ValueError, OSError) as e:
            logger.error("Pipeline execution failed: %s", e)
            return False

    def register_mlflow_run(
        self,
        trigger: str,
        trigger_detail: str,
        metrics: dict[str, float],
    ) -> str | None:
        """
        Tag the latest MLflow run and return the run ID.

        Args:
            trigger: Trigger type ("drift" or "feedback_volume")
            trigger_detail: Human-readable trigger description
            metrics: Evaluation metrics dict

        Returns:
            MLflow run ID string, or None if unavailable
        """
        if not MLFLOW_AVAILABLE:
            logger.warning("MLflow not available — skipping run registration")
            return None

        try:
            mlflow.set_tracking_uri(self.mlflow_tracking_uri)
            mlflow.set_experiment(self.mlflow_experiment)

            experiment = mlflow.get_experiment_by_name(self.mlflow_experiment)
            if experiment is None:
                logger.warning(
                    "MLflow experiment '%s' not found", self.mlflow_experiment
                )
                return None

            # Find the latest run in the experiment
            runs = mlflow.search_runs(
                experiment_ids=[experiment.experiment_id],
                order_by=["start_time DESC"],
                max_results=1,
            )

            if runs.empty:
                logger.warning("No MLflow runs found to tag")
                return None

            run_id = runs.iloc[0]["run_id"]
            with mlflow.start_run(run_id=run_id):
                mlflow.set_tag("trigger", trigger)
                mlflow.set_tag("trigger_detail", trigger_detail[:200])
                mlflow.set_tag("is_candidate", "true")

                # Log trigger metrics
                for k, v in metrics.items():
                    if isinstance(v, (int, float)):
                        mlflow.log_metric(f"candidate_{k}", v)

            logger.info(
                "MLflow run %s tagged as candidate (trigger=%s)", run_id[:12], trigger
            )
            return run_id

        except (RuntimeError, ValueError, OSError) as e:
            logger.warning("MLflow run registration failed: %s", e)
            return None

    def extract_metrics(self) -> dict[str, float] | None:
        """
        Extract evaluation metrics from the latest training run.

        Reads from reports/final_results.json generated by run_pipeline.py.

        Returns:
            Dict with pr_auc, f1, precision, recall, threshold or None
        """
        reports_dir = self.models_dir.parent / "reports"
        results_path = reports_dir / "final_results.json"

        if results_path.exists():
            try:
                with open(results_path) as f:
                    results = json.load(f)
                metrics = results.get("metrics", {})
                return {
                    "pr_auc": metrics.get("pr_auc", 0.0),
                    "f1": metrics.get("f1", 0.0),
                    "precision": metrics.get("precision", 0.0),
                    "recall": metrics.get("recall", 0.0),
                    "threshold": results.get("best_threshold", 0.5),
                    "model_name": results.get("best_model", "unknown"),
                }
            except (json.JSONDecodeError, KeyError) as e:
                logger.warning("Failed to read final_results.json: %s", e)

        # Fallback: read comparison CSV
        csv_path = reports_dir / "model_comparison_fraud.csv"
        if csv_path.exists():
            try:
                df = pd.read_csv(csv_path)
                if not df.empty:
                    best = df.iloc[0]
                    return {
                        "pr_auc": float(best.get("PR-AUC", 0.0)),
                        "f1": float(best.get("F1", 0.0)),
                        "precision": float(best.get("Precision", 0.0)),
                        "recall": float(best.get("Recall", 0.0)),
                        "threshold": float(best.get("Threshold", 0.5)),
                        "model_name": best.get("Model", "unknown"),
                    }
            except (RuntimeError, ValueError, OSError) as e:
                logger.warning("Failed to read comparison CSV: %s", e)

        return None

    def generate_candidate_version(self) -> str:
        """Generate a candidate version string."""
        now = datetime.utcnow()
        return now.strftime("v%Y%m%d_%H%M%S")

    def trigger(
        self,
        recent_drift_events: list[dict[str, Any]] | None = None,
        new_feedback_count: int | None = None,
        dry_run: bool = False,
    ) -> TriggerResult:
        """
        Check conditions and, if triggered, run retraining pipeline.

        Args:
            recent_drift_events: Optional list of recent drift events from DB
            new_feedback_count: Optional count of new feedback since last training
            dry_run: If True, check conditions but don't run pipeline

        Returns:
            TriggerResult with outcome details
        """
        # Step 1: Check conditions
        check = self.check_conditions(recent_drift_events, new_feedback_count)

        if not check["any_triggered"]:
            logger.info("Retraining not triggered: %s", check["primary_reason"])
            return TriggerResult(
                triggered=False,
                reason=check["primary_reason"],
                trigger_metrics=check,
            )

        logger.info("Retraining triggered: %s", check["primary_reason"])

        if dry_run:
            return TriggerResult(
                triggered=True,
                reason=check["primary_reason"],
                trigger_metrics=check,
                candidate_version=self.generate_candidate_version(),
            )

        # Step 2: Run the training pipeline
        pipeline_ok = self.run_pipeline()
        if not pipeline_ok:
            return TriggerResult(
                triggered=True,
                reason=check["primary_reason"],
                trigger_metrics=check,
                error="Training pipeline failed",
            )

        # Step 3: Extract metrics from training output
        metrics = self.extract_metrics()
        if metrics is None:
            return TriggerResult(
                triggered=True,
                reason=check["primary_reason"],
                trigger_metrics=check,
                error="Failed to extract metrics after training",
            )

        # Step 4: Register in MLflow
        trigger_type = (
            "drift" if check["conditions"]["drift"]["met"] else "feedback_volume"
        )
        mlflow_run_id = self.register_mlflow_run(
            trigger=trigger_type,
            trigger_detail=check["primary_reason"],
            metrics=metrics,
        )

        # Step 5: Generate candidate version
        candidate_version = self.generate_candidate_version()

        logger.info(
            "Retraining complete: candidate=%s trigger=%s pr_auc=%.4f mlflow_run=%s",
            candidate_version,
            trigger_type,
            metrics.get("pr_auc", 0.0),
            mlflow_run_id or "N/A",
        )

        return TriggerResult(
            triggered=True,
            reason=check["primary_reason"],
            candidate_version=candidate_version,
            trigger_metrics=check,
            candidate_metrics=metrics,
        )


# Standalone CLI Entrypoint


def check_and_trigger(
    feedback_threshold: int | None = None,
    drift_critical_threshold: int | None = None,
    dry_run: bool = False,
) -> TriggerResult:
    """
    Convenience function to check conditions and trigger retraining.

    Reads configuration from environment variables:
    - RETRAINING_FEEDBACK_THRESHOLD (default: 100)
    - RETRAINING_DRIFT_CRITICAL_THRESHOLD (default: 3)
    - RETRAINING_DRY_RUN (set to "true" for dry run)

    Args:
        feedback_threshold: Override for feedback volume threshold
        drift_critical_threshold: Override for drift event threshold
        dry_run: If True, check conditions but don't run pipeline

    Returns:
        TriggerResult with outcome details
    """
    trigger = RetrainingTrigger(
        feedback_threshold=feedback_threshold
        or int(os.environ.get("RETRAINING_FEEDBACK_THRESHOLD", "100")),
        drift_critical_threshold=drift_critical_threshold
        or int(os.environ.get("RETRAINING_DRIFT_CRITICAL_THRESHOLD", "3")),
    )
    return trigger.trigger(dry_run=dry_run)


def run_retraining_pipeline() -> None:
    """
    Main entry point for K8s CronJob execution.

    Called as:
        python -m src.fraudlens.retraining.retrain_trigger

    Reads config from environment and logs results for CloudWatch/journald.
    """
    logging.basicConfig(
        level=getattr(logging, os.environ.get("LOG_LEVEL", "INFO").upper()),
        format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
    )

    dry_run = os.environ.get("RETRAINING_DRY_RUN", "").lower() == "true"

    logger.info("Retraining trigger check starting (dry_run=%s)...", dry_run)

    result = check_and_trigger(dry_run=dry_run)

    if result.error:
        logger.error("Retraining failed: %s", result.error)
        sys.exit(1)

    if result.triggered:
        logger.info(
            "Retraining triggered: %s | candidate=%s | metrics=%s",
            result.reason,
            result.candidate_version or "N/A",
            json.dumps(result.candidate_metrics or {}),
        )
    else:
        logger.info("Retraining not triggered: %s", result.reason)

    # Output JSON summary to stdout for logging
    summary = {
        "triggered": result.triggered,
        "reason": result.reason,
        "candidate_version": result.candidate_version,
        "candidate_metrics": result.candidate_metrics,
        "error": result.error,
    }
    print(json.dumps(summary, indent=2))


if __name__ == "__main__":
    run_retraining_pipeline()
